(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function page(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===id));location.hash=id==='home'?'':id;$('#navlinks')?.classList.remove('open');scrollTo({top:0,behavior:'instant'});if(id==='anatomy')renderAnatomy();if(id==='stroke')renderStroke()}
$$('[data-page]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();page(b.dataset.page)}));$('#hamb').onclick=()=>$('#navlinks').classList.toggle('open');const hash=location.hash.slice(1);if(hash&&$('#'+hash))page(hash);

const imgs={};Object.entries(ATLAS).forEach(([k,src])=>{const im=new Image();im.crossOrigin='anonymous';im.src=src;imgs[k]=im});
const [NX,NY,NZ]=CT_MANIFEST.dims;let vol=new Uint8Array(0),validY=[],volumeStatus='loading';
function nonblankYs(){const a=[];if(!vol.length)return a;for(let y=0;y<NY;y++){let nz=0;for(let z=0;z<NZ;z+=4)for(let x=0;x<NX;x+=4)nz+=vol[x+NX*y+NX*NY*z]>2;if(nz>30)a.push(y)}return a}
fetch(CT_URL).then(r=>{if(!r.ok)throw Error(r.status);return r.arrayBuffer()}).then(b=>{vol=new Uint8Array(b);validY=nonblankYs();volumeStatus='ready';const st=studies.find(x=>x.id==='brainVol');st.count=Math.max(1,validY.length);st.sub=validY.length+' source-covered levels';setupStudies();renderAnatomy();renderStroke()}).catch(e=>{console.error(e);volumeStatus='error'});

function renderAtlas(canvas,key,frame,cols=6,rows=4,opt={}){const img=imgs[key],ctx=canvas.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,canvas.width,canvas.height);if(!img||!img.complete||!img.naturalWidth){if(img)img.onload=()=>renderAtlas(canvas,key,frame,cols,rows,opt);ctx.fillStyle='#9ce8cb';ctx.font='600 16px system-ui';ctx.textAlign='center';ctx.fillText('Loading real CT stack…',canvas.width/2,canvas.height/2);return}const fw=img.naturalWidth/cols,fh=img.naturalHeight/rows,sx=(frame%cols)*fw,sy=Math.floor(frame/cols)*fh;const off=document.createElement('canvas');off.width=fw;off.height=fh;const oc=off.getContext('2d');oc.drawImage(img,sx,sy,fw,fh,0,0,fw,fh);if(opt.invert){oc.globalCompositeOperation='difference';oc.fillStyle='#fff';oc.fillRect(0,0,fw,fh);oc.globalCompositeOperation='source-over'}const sc=Math.min(canvas.width/fw,canvas.height/fh)*.96*(opt.zoom||1);ctx.save();ctx.translate(canvas.width/2+(opt.panX||0),canvas.height/2+(opt.panY||0));ctx.drawImage(off,-fw*sc/2,-fh*sc/2,fw*sc,fh*sc);ctx.restore()}
function renderVolume(canvas,y,opt={}){const ctx=canvas.getContext('2d');ctx.fillStyle='#000';ctx.fillRect(0,0,canvas.width,canvas.height);if(!vol.length||!validY.length){ctx.fillStyle='#9ce8cb';ctx.font='600 16px system-ui';ctx.textAlign='center';ctx.fillText(volumeStatus==='error'?'Volume unavailable':'Loading full CT volume…',canvas.width/2,canvas.height/2);return}y=Math.max(0,Math.min(NY-1,y|0));const tmp=document.createElement('canvas');tmp.width=NX;tmp.height=NZ;const tc=tmp.getContext('2d'),im=tc.createImageData(NX,NZ);let p=0;for(let row=0;row<NZ;row++){const z=NZ-1-row;for(let x=0;x<NX;x++){let v=vol[x+NX*y+NX*NY*z];if(opt.invert)v=255-v;im.data[p++]=v;im.data[p++]=v;im.data[p++]=v;im.data[p++]=255}}tc.putImageData(im,0,0);const sc=Math.min(canvas.width/NX,canvas.height/NZ)*.94*(opt.zoom||1);ctx.save();ctx.translate(canvas.width/2+(opt.panX||0),canvas.height/2+(opt.panY||0));ctx.imageSmoothingEnabled=true;ctx.drawImage(tmp,-NX*sc/2,-NZ*sc/2,NX*sc,NZ*sc);ctx.restore()}

let heroPos=12;const hero=$('#heroCanvas');function heroDraw(){renderAtlas(hero,'adult-head-plain-v1.webp',heroPos,4,6);$('#heroSlice').textContent='SLICE '+(heroPos+1)+'/24'}function heroMove(d){heroPos=Math.max(0,Math.min(23,heroPos+d));heroDraw()}heroDraw();$('#heroViewer').addEventListener('wheel',e=>{e.preventDefault();heroMove(e.deltaY>0?1:-1)},{passive:false});let hd=null;$('#heroViewer').addEventListener('pointerdown',e=>hd=e.clientY);window.addEventListener('pointerup',()=>hd=null);window.addEventListener('pointermove',e=>{if(hd!==null&&Math.abs(e.clientY-hd)>7){heroMove(e.clientY>hd?1:-1);hd=e.clientY}});

const studies=[
{id:'headRef',name:'Head CT — high-res',sub:'24 real CC0 frames',kind:'atlas',asset:'adult-head-plain-v1.webp',count:24,cols:4,rows:6,preset:'NCCT · 4 mm pre-windowed',note:'Mikael Häggström normal head CT teaching series, CC0.',labels:[['Posterior fossa','Temporal bones','Brainstem'],['Basal cisterns','Sylvian fissures','Temporal lobes'],['Basal ganglia','Internal capsules','Lateral ventricles'],['Centrum semiovale','Cortex','Falx']]},
{id:'brainVol',name:'Head CT — volumetric',sub:'loading real volume',kind:'volume',count:1,preset:'Brain display · source grid',note:'NLM Visible Human head grid via Neuroaxis Atlas. Source-covered levels only.',labels:[['Skull base','Cerebellum / brainstem','Basal cisterns'],['Temporal lobes','Basal ganglia','Third ventricle'],['Lateral ventricles','Deep grey nuclei','Insular cortex'],['Centrum semiovale','Cortical sulci','Falx']]},
{id:'chest',name:'Chest CT — lung',sub:'24 real frames',kind:'atlas',asset:'chest-plain-v1.webp',count:24,cols:6,rows:4,preset:'Lung · W1500 / L−600',note:'AortaSeg-60 Nat_07 adult noncontrast reference sequence.',labels:[['Lungs','Pleural surfaces','Vertebral body'],['Main bronchi','Pulmonary vessels','Descending aorta'],['Hila','Heart / mediastinum','Fissures'],['Upper lungs','Trachea','Great vessels']]},
{id:'abdomen',name:'Abdomen CT',sub:'24 real frames',kind:'atlas',asset:'abdomen-plain-v1.webp',count:24,cols:6,rows:4,preset:'Soft tissue · W400 / L40',note:'AortaSeg-60 Nat_07 adult abdominal reference sequence.',labels:[['Liver','Spleen','Stomach'],['Pancreas','Kidneys','Aorta / IVC'],['Bowel','Mesentery','Psoas muscles'],['Lower abdomen','Bowel','Pelvic brim']]},
{id:'renal',name:'Renal levels',sub:'24 real frames',kind:'atlas',asset:'urinary-plain-v1.webp',count:24,cols:6,rows:4,preset:'Soft tissue · W400 / L40',note:'Real renal-level CT reference stack; not a pathology case.',labels:[['Kidneys','Renal sinus','Psoas'],['Ureters where visible','Aorta / IVC','Bowel'],['Lower poles','Retroperitoneum','Lumbar spine'],['Pelvic ureter course','Iliac vessels','Bowel']]},
{id:'pelvis',name:'Lumbar / pelvis',sub:'24 real frames',kind:'atlas',asset:'lumbar-pelvis-plain-v1.webp',count:24,cols:6,rows:4,preset:'Bone display · W1600 / L450',note:'Real lumbar/pelvic CT reference stack.',labels:[['Lumbar vertebra','Psoas','Posterior elements'],['Sacrum','Iliac bones','SI joints'],['Acetabula','Pelvic organs','Gluteal muscles'],['Femoral heads','Pelvic ring','Soft tissues']]},
{id:'aorta',name:'Aortic CTA',sub:'24 real frames',kind:'atlas',asset:'aorta-cta-v1.webp',count:24,cols:6,rows:4,preset:'CTA reference',note:'Real aortic CTA acquisition reference; vessel anatomy teaching only.',labels:[['Aorta','Branch vessels','Mediastinum'],['Descending aorta','Pulmonary arteries','Vertebral body'],['Abdominal aorta','Visceral branches','IVC'],['Aortic bifurcation','Iliac arteries','Pelvic vessels']]},
{id:'neckcta',name:'Head / neck CTA',sub:'24 real frames',kind:'atlas',asset:'adult-neck-cta-v1.webp',count:24,cols:6,rows:4,preset:'CTA reference',note:'Real head/neck CTA reference sequence.',labels:[['Carotids','Vertebrals','Airway'],['Carotid bifurcation','Jugular veins','C-spine'],['Intracranial ICA','Basilar artery','Skull base'],['Circle of Willis region','MCA / ACA origins','Venous structures']]}
];
let anat={study:0,slice:12,invert:false,labels:true,zoom:1,panX:0,panY:0};
function setupStudies(){const el=$('#studyList');if(!el)return;el.innerHTML='<h4>Study</h4>'+studies.map((s,i)=>'<button class="study '+(i===anat.study?'active':'')+'" data-study="'+i+'">'+s.name+'<small>'+s.sub+'</small></button>').join('');$$('[data-study]').forEach(b=>b.onclick=()=>{anat.study=+b.dataset.study;anat.slice=Math.floor(studies[anat.study].count/2);setupStudies();renderAnatomy()})}
function levelLabels(s,i){return s.labels[Math.min(3,Math.floor((i/Math.max(1,s.count))*4))]||s.labels[0]}
function renderAnatomy(){const c=$('#scanCanvas');if(!c)return;const s=studies[anat.study];anat.slice=Math.max(0,Math.min(Math.max(0,s.count-1),anat.slice));if(s.kind==='volume')renderVolume(c,validY[anat.slice]??0,anat);else renderAtlas(c,s.asset,anat.slice,s.cols,s.rows,anat);$('#sliceRange').max=Math.max(0,s.count-1);$('#sliceRange').value=anat.slice;$('#sliceVal').textContent=s.kind==='volume'&&volumeStatus!=='ready'?'Loading…':(anat.slice+1)+' / '+s.count;$('#stackProgress').style.width=(s.count?((anat.slice+1)/s.count*100):0)+'%';$('#presetMeta').textContent=s.preset;$('#sourceNote').textContent=s.note;$('#scanMeta').textContent=s.name+'\nAXIAL · REFERENCE';$('#scanRight').textContent='Slice '+(anat.slice+1)+'/'+s.count+'\nR ← → L';$('#labelList').innerHTML=levelLabels(s,anat.slice).map(x=>'<li>'+x+'</li>').join('');$('#labelBox').classList.toggle('on',anat.labels);buildQuiz(s)}
function moveSlice(d){anat.slice=Math.max(0,Math.min(studies[anat.study].count-1,anat.slice+d));renderAnatomy()}
setupStudies();renderAnatomy();$('#sliceRange').oninput=e=>{anat.slice=+e.target.value;renderAnatomy()};$('#labelsBtn').onclick=()=>{anat.labels=!anat.labels;$('#labelsBtn').classList.toggle('active',anat.labels);renderAnatomy()};$('#invertBtn').onclick=()=>{anat.invert=!anat.invert;$('#invertBtn').classList.toggle('active',anat.invert);renderAnatomy()};$('#resetBtn').onclick=()=>{anat.invert=false;anat.slice=Math.floor(studies[anat.study].count/2);$('#invertBtn').classList.remove('active');renderAnatomy()};$('#pacs').addEventListener('wheel',e=>{e.preventDefault();moveSlice(e.deltaY>0?1:-1)},{passive:false});$('#pacs').addEventListener('keydown',e=>{if(['ArrowRight','ArrowDown'].includes(e.key)){e.preventDefault();moveSlice(1)}if(['ArrowLeft','ArrowUp'].includes(e.key)){e.preventDefault();moveSlice(-1)}});
let sd=null;$('#scanCanvas').addEventListener('pointerdown',e=>sd=e.clientY);window.addEventListener('pointermove',e=>{if(sd!==null&&Math.abs(e.clientY-sd)>8){moveSlice(e.clientY>sd?1:-1);sd=e.clientY}});window.addEventListener('pointerup',()=>sd=null);
function buildQuiz(s){const vals=levelLabels(s,anat.slice),correct=vals[0],pool=['Basal ganglia','Pleural surface','Pancreas','Aortic bifurcation','Cerebellum','Psoas muscles','Carotid artery','Lateral ventricle'].filter(x=>!vals.includes(x));const opts=[correct,pool[(anat.slice+anat.study)%pool.length],pool[(anat.slice+anat.study+3)%pool.length]].sort(()=>Math.random()-.5);$('#quizQ').textContent='Which structure/group belongs on your review at this level?';$('#quizOpts').innerHTML=opts.map(o=>'<button class="tool qopt" data-ok="'+(o===correct)+'">'+o+'</button>').join('');$('#quizAnswer').className='answer';$$('.qopt').forEach(b=>b.onclick=()=>{$('#quizAnswer').textContent=b.dataset.ok==='true'?'Correct — '+correct+'.':'Review this level: '+vals.join(', ')+'.';$('#quizAnswer').className='answer show'})}

const cases=[
{id:'lvo',cat:'Neuro',title:'Large-vessel occlusion stroke',mod:'NCCT + CTA',urg:'Time-critical',ref:'brainVol',summary:'Exclude haemorrhage, identify early ischaemic change, then define the vascular occlusion question.',find:'Haemorrhage; loss of grey–white differentiation; sulcal effacement; hyperdense artery; CTA cut-off or asymmetric vessel filling.',question:'Intracranial haemorrhage? Early ischaemic change? Large-vessel occlusion and site?',action:'Activate the local stroke pathway early and escalate for specialist/Telestroke review.'},
{id:'ich',cat:'Neuro',title:'Intracerebral haemorrhage',mod:'NCCT brain',urg:'Immediate escalation',ref:'headRef',summary:'Acute blood is typically hyperdense on noncontrast CT; location and mass effect matter.',find:'Blood location, size, intraventricular extension, hydrocephalus, midline shift and herniation signs.',question:'Acute haemorrhage? Location, mass effect, IVH or hydrocephalus?',action:'Urgent senior/stroke/neurosurgical escalation; follow local anticoagulant reversal and ICH pathways.'},
{id:'early',cat:'Neuro',title:'Early ischaemic stroke',mod:'NCCT brain',urg:'Time-critical',ref:'brainVol',summary:'A subtle or initially normal NCCT does not exclude acute ischaemia.',find:'Loss of grey–white differentiation, insular ribbon obscuration, lentiform obscuration, sulcal effacement, hyperdense artery.',question:'Haemorrhage? Early ischaemic change or established infarction?',action:'Pair NCCT with the clinical time window and required vascular imaging.'},
{id:'pe',cat:'Chest',title:'Pulmonary embolism',mod:'CTPA',urg:'Urgent if unstable',ref:'chest',summary:'CTPA is a dedicated pulmonary arterial examination, not simply a routine contrast CT chest.',find:'Pulmonary arterial filling defects, right-heart strain features, infarction/effusion and alternative thoracic pathology.',question:'Pulmonary embolism? Central clot burden? Right-heart strain features?',action:'If unstable, manage and escalate as a resuscitation problem while imaging decisions are made.'},
{id:'ptx',cat:'Chest',title:'Pneumothorax',mod:'CXR ± CT',urg:'Clinical urgency first',ref:'chest',summary:'Usually a radiographic diagnosis; CT is mainly for uncertainty or complex anatomy.',find:'Pleural line, absent peripheral markings, size/tension clues and associated injury.',question:'Pneumothorax? Tension physiology? Associated thoracic injury?',action:'Do not delay emergency decompression for imaging if the clinical picture is tension pneumothorax.'},
{id:'aaa',cat:'Abdomen',title:'Ruptured abdominal aortic aneurysm',mod:'CTA / CT A/P',urg:'Emergency',ref:'aorta',summary:'Aortic calibre, mural findings and retroperitoneal blood are key.',find:'Aneurysm, retroperitoneal haematoma, active extravasation, focal wall discontinuity and branch anatomy.',question:'AAA with rupture or impending rupture? Anatomy relevant to vascular management?',action:'Urgent vascular/surgical escalation; imaging pathway depends on stability.'},
{id:'sbo',cat:'Abdomen',title:'Small bowel obstruction',mod:'CT abdomen/pelvis',urg:'Urgent if complicated',ref:'abdomen',summary:'The important question is obstruction plus whether there are signs of ischaemia or closed loop.',find:'Dilated small bowel, transition point, closed-loop configuration, reduced enhancement, mesenteric oedema, pneumatosis or free gas.',question:'SBO? Transition point? Closed loop, ischaemia or perforation?',action:'Escalate urgently for peritonitis, strangulation, ischaemia or perforation.'},
{id:'appendix',cat:'Abdomen',title:'Appendicitis',mod:'US / CT depending context',urg:'Clinical pathway',ref:'abdomen',summary:'Imaging choice depends on age, pregnancy, local pathway and pre-test probability.',find:'Appendiceal dilatation, wall thickening/enhancement, periappendiceal inflammation, appendicolith, collection or perforation.',question:'Appendicitis? Complication or alternative cause?',action:'Use local surgical and imaging pathways; avoid treating CT as a substitute for clinical review.'},
{id:'ces',cat:'Spine',title:'Cauda equina syndrome',mod:'MRI spine',urg:'Emergency pathway',ref:'pelvis',summary:'The key imaging test for suspected compressive cauda equina pathology is urgent MRI.',find:'Canal compromise and the causative lesion; CT or plain films do not exclude CES.',question:'Compressive cauda equina pathology and level/cause?',action:'Urgent spinal pathway and MRI; communicate bladder/bowel/saddle symptoms and objective deficit.'}
];
let filter='All';function refStudy(id){return studies.find(x=>x.id===id)||studies[0]}
function drawCase(canvas,c){const s=refStudy(c.ref);if(s.kind==='volume')renderVolume(canvas,validY[Math.floor(validY.length*.55)]??0);else renderAtlas(canvas,s.asset,Math.floor(s.count*.52),s.cols,s.rows)}
function renderCases(){const cats=['All',...new Set(cases.map(c=>c.cat))];$('#caseFilters').innerHTML=cats.map(x=>'<button class="filter '+(x===filter?'active':'')+'" data-filter="'+x+'">'+x+'</button>').join('');$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderCases()});const list=filter==='All'?cases:cases.filter(c=>c.cat===filter);$('#caseGrid').innerHTML=list.map(c=>'<article class="case" data-case="'+c.id+'"><div class="casevisual"><canvas width="512" height="300" id="cv-'+c.id+'"></canvas><span class="tag">'+c.mod+'</span><span class="refnote">reference anatomy</span></div><div class="casebody"><h3>'+c.title+'</h3><p>'+c.summary+'</p><div class="casefoot"><span>'+c.cat+'</span><span>'+c.urg+'</span></div></div></article>').join('');list.forEach(c=>drawCase($('#cv-'+c.id),c));$$('[data-case]').forEach(x=>x.onclick=()=>openCase(x.dataset.case))}
function openCase(id){const c=cases.find(x=>x.id===id);$('#drawerContent').innerHTML='<div class="eyebrow">'+c.cat+' · '+c.mod+'</div><h2 style="margin:8px 0 10px">'+c.title+'</h2><p class="muted">'+c.summary+'</p><div class="drawergrid"><div class="fact"><b>What to look for</b><p>'+c.find+'</p></div><div class="fact"><b>Ask radiology</b><p>'+c.question+'</p></div><div class="fact"><b>What happens next</b><p>'+c.action+'</p></div><div class="fact"><b>JMO habit</b><p>State the time course, relevant physiology, key examination findings, treatment already given and exactly what result will change management.</p></div></div><div class="alert">Educational summary only. Current local protocols, senior review and the formal radiology report take precedence.</div>';$('#drawer').classList.add('open')}
$('#closeDrawer').onclick=()=>$('#drawer').classList.remove('open');$('#drawer').addEventListener('click',e=>{if(e.target===$('#drawer'))$('#drawer').classList.remove('open')});renderCases();

const stroke=[
{title:'1 · NCCT',sub:'Blood first; then early ischaemia',type:'vol',body:'<h3>Start with the noncontrast CT.</h3><p>Ask first: <b>is there haemorrhage?</b> Then deliberately inspect grey–white differentiation, the insular ribbon, basal ganglia, sulci, ventricles and any hyperdense artery.</p><div class="callout">A normal-looking early NCCT does not exclude acute ischaemia. The clinical time window and vascular question still matter.</div>'},
{title:'2 · CTA',sub:'Where is the vessel problem?',type:'cta',body:'<h3>Define the vascular question.</h3><p>Trace the carotid and vertebrobasilar systems into the intracranial circulation. Look for abrupt cut-off or convincing asymmetry rather than staring at one image.</p><div class="alert">The CTA shown here is a real teaching/reference acquisition, not a positive LVO case.</div>'},
{title:'3 · Communicate',sub:'Time, deficit, imaging, next action',type:'text',body:'<h3>The handoff should make the clock visible.</h3><p>Include time/last known well, deficit, relevant anticoagulation/bleeding context, imaging status and exactly what specialist input you need.</p><div class="request">Acute focal neurological deficit. Last known well: [time]. Current deficit: [brief description / NIHSS if used locally]. NCCT: [key result]. CTA: [performed/pending; key result if confirmed]. Anticoagulation/major bleeding context: [detail]. Requesting urgent stroke specialist/Telestroke review and reperfusion-pathway advice.</div>'}
];let strokeI=0,strokeSlice=0,ctaSlice=11;
function setupStroke(){$('#strokeSteps').innerHTML=stroke.map((s,i)=>'<div class="step '+(i===strokeI?'active':'')+'" data-stroke="'+i+'"><b>'+s.title+'</b><small>'+s.sub+'</small></div>').join('');$$('[data-stroke]').forEach(x=>x.onclick=()=>{strokeI=+x.dataset.stroke;renderStroke()})}
function renderStroke(){const s=stroke[strokeI],c=$('#strokeCanvas');if(!c)return;setupStroke();$('#strokeContent').innerHTML=s.body;if(s.type==='vol'){if(validY.length&&strokeSlice===0)strokeSlice=Math.floor(validY.length*.55);renderVolume(c,validY[strokeSlice]??0);$('#strokeMeta').textContent='REAL NCCT REFERENCE\nSlice '+(strokeSlice+1)+'/'+Math.max(1,validY.length)}else if(s.type==='cta'){renderAtlas(c,'adult-neck-cta-v1.webp',ctaSlice,6,4);$('#strokeMeta').textContent='REAL CTA REFERENCE\nFrame '+(ctaSlice+1)+'/24'}else{const x=c.getContext('2d');x.fillStyle='#020504';x.fillRect(0,0,c.width,c.height);x.fillStyle='#9ce8cb';x.font='700 40px system-ui';x.textAlign='center';x.fillText('CALL EARLY',256,235);x.fillStyle='#819a92';x.font='15px ui-monospace';x.fillText('time · deficit · imaging · next action',256,275);$('#strokeMeta').textContent='COMMUNICATION'}}
$('#strokeCanvas').addEventListener('wheel',e=>{e.preventDefault();if(stroke[strokeI].type==='vol'&&validY.length)strokeSlice=Math.max(0,Math.min(validY.length-1,strokeSlice+(e.deltaY>0?1:-1)));else if(stroke[strokeI].type==='cta')ctaSlice=Math.max(0,Math.min(23,ctaSlice+(e.deltaY>0?1:-1)));renderStroke()},{passive:false});renderStroke();

const scenario={stroke:{h:['last known well / onset','deficit + side','anticoagulants'],q:['haemorrhage?','LVO/site?','early ischaemic change?']},pe:{h:['onset + hypoxia','pre-test probability','DVT signs'],q:['pulmonary embolism?','right-heart strain?','alternative cause?']},abdo:{h:['pain site/onset','operations','peritonism/obs'],q:['obstruction?','perforation?','inflammation/collection?']},renal:{h:['side/radiation','haematuria','single kidney/fever'],q:['ureteric calculus?','size/location?','hydronephrosis?']},cauda:{h:['saddle symptoms','bladder/bowel change','objective weakness/reflexes'],q:['compressive cauda equina pathology?']},sepsis:{h:['source clues','cultures/antibiotics','recent procedure'],q:['occult source?','drainable collection?','complication?']},free:{h:['onset/timing','relevant treatment','key negatives'],q:['state the decision-changing question']}};
function tips(){const s=scenario[$('#reqScenario').value];$('#historyTips').innerHTML=s.h.map(t=>'<span class="tip" data-target="reqHistory">+ '+t+'</span>').join('');$('#questionTips').innerHTML=s.q.map(t=>'<span class="tip" data-target="reqQuestion">+ '+t+'</span>').join('');$$('.tip').forEach(t=>t.onclick=()=>{const a=$('#'+t.dataset.target);a.value+=(a.value.trim()?'; ':'')+t.textContent.slice(2)})}$('#reqScenario').onchange=tips;tips();
$('#buildReq').onclick=()=>{const study=$('#reqStudy').value,h=$('#reqHistory').value.trim(),e=$('#reqExam').value.trim(),l=$('#reqLabs').value.trim(),q=$('#reqQuestion').value.trim();$('#requestOut').textContent=study.toUpperCase()+'\n\nClinical history: '+(h||'[add concise history and timing]')+'\nRelevant exam/observations: '+(e||'[add relevant positives/negatives]')+'\nRelevant labs / safety context: '+(l||'[add relevant contrast/MRI safety context]')+'\n\nClinical question: '+(q||'[state what the scan needs to answer]')+'\n\nPlease correlate with prior imaging where relevant.'};$('#copyReq').onclick=async()=>{try{await navigator.clipboard.writeText($('#requestOut').textContent);$('#copyMsg').textContent='Copied'}catch(e){$('#copyMsg').textContent='Select and copy manually'}setTimeout(()=>$('#copyMsg').textContent='',1500)};

const tools={
scan:'<div class="guides"><article class="guide"><h3>Acute focal neurology</h3><p>Question: blood, established ischaemia and vessel occlusion. Follow the local stroke imaging pathway.</p></article><article class="guide"><h3>Suspected PE</h3><p>Question: pulmonary arterial thrombus and complications. CTPA is a dedicated protocol.</p></article><article class="guide"><h3>Renal colic</h3><p>Question: stone, site, size, obstruction and alternative diagnosis.</p></article><article class="guide"><h3>Possible cauda equina</h3><p>Question: compressive neural pathology. This is an urgent MRI pathway.</p></article></div>',
call:'<div class="roundgrid"><div class="formpanel"><h3>Before you call radiology</h3><div class="check"><i>01</i><span>Patient location and how unwell they are.</span></div><div class="check"><i>02</i><span>One-line clinical story plus onset/timing.</span></div><div class="check"><i>03</i><span>Key examination change.</span></div><div class="check"><i>04</i><span>Exact imaging question and urgency.</span></div><div class="check"><i>05</i><span>Relevant contrast/MRI safety context.</span></div></div><div class="outputpanel"><div class="request">Hi, I’m the JMO/RMO from [ward/ED]. The key issue is [one line]. Timing is [x]. Examination/observations: [key findings]. I’m concerned about [diagnosis]. We’re asking whether [study] is appropriate/urgent and whether you recommend a different protocol.</div></div></div>',
report:'<div class="guides"><article class="guide"><h3>No acute intracranial abnormality</h3><p>This does not mean no neurological disease; it means no acute structural CT finding was reported.</p></article><article class="guide"><h3>Indeterminate / correlate clinically</h3><p>Ask what uncertainty remains and whether follow-up or another modality is needed.</p></article><article class="guide"><h3>Incidental finding</h3><p>Read the recommendation, establish ownership and close the follow-up loop.</p></article><article class="guide"><h3>Critical finding</h3><p>Document who received the result, when, what action occurred and who owns the next step.</p></article></div>',
safety:'<div class="guides"><article class="guide"><h3>Iodinated contrast</h3><p>Consider prior severe reaction, renal context where relevant, urgency/benefit, pregnancy where relevant and current local policy.</p></article><article class="guide"><h3>MRI</h3><p>Clarify devices/metal, prior surgery, foreign-body risk, ability to lie still and urgency. Device-specific MRI conditions matter.</p></article></div><div class="alert">Use current RANZCR and local guidance for real patient decisions.</div>',
critical:'<div class="roundgrid"><div class="formpanel"><h3>Critical result loop</h3><div class="check"><i>01</i><span>Read the report / speak with radiology if needed.</span></div><div class="check"><i>02</i><span>Identify who must act now.</span></div><div class="check"><i>03</i><span>Escalate based on physiology and diagnosis.</span></div><div class="check"><i>04</i><span>Document time, recipient, advice and action.</span></div><div class="check"><i>05</i><span>Reassess and confirm the plan occurred.</span></div></div><div class="outputpanel"><div class="request">Imaging result: [critical finding]. Radiology communicated at [time]. [Senior/specialty] notified at [time]. Immediate plan: [action]. Patient currently: [status]. Outstanding: [next step], owned by [team/person].</div></div></div>'
};Object.entries(tools).forEach(([k,v])=>$('#tool-'+k).innerHTML=v);$$('[data-tool]').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$$('.toolpanel').forEach(x=>x.classList.remove('active'));$('#tool-'+b.dataset.tool).classList.add('active')});
})();